[tool.poetry]
name = "PowerFlow"
version = "0.1.0"
description = ""
authors = ["Felipe Markson <fmarkson@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
"OpenDSSDirect.py" = {extras = ["extras"], version = "^0.3.7"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
test = "scripts-poetry:test"